name: Publish Npm Package
on:
  pull_request:
    branches: [master]
    types:
      - closed
jobs:
  libs-npm:
    if: github.event.pull_request.merged == true
    uses: kne-union/actions/.github/workflows/publish-libs-workflow.yml@master
    secrets: inherit
    with:
      package_name: '@kne/system-layout'
      example_package_name: '@kne-components/system-layout'
